// <auto-generated />
namespace BlogDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ClasesBase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClasesBase));
        
        string IMigrationMetadata.Id
        {
            get { return "201801162335291_ClasesBase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
