// <auto-generated />
namespace BlogDemo.Servicios.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PostClassupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PostClassupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201801170010081_Post Class update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
